<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>WWP.Ukrainian</AssemblyName>
    <RootNamespace>WWP.Ukrainian</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ReferenceDir>$(MSBuildThisFileDirectory)..\..\lib</ReferenceDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>$(ReferenceDir)\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(ReferenceDir)\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(ReferenceDir)\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(ReferenceDir)\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ReferenceDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>$(ReferenceDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ReferenceDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="I2Loc">
      <HintPath>$(ReferenceDir)\I2Loc.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Core">
      <HintPath>$(ReferenceDir)\Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UI">
      <HintPath>$(ReferenceDir)\UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
